---
title: "Drzewa klasyfikacyjne"
author: "Michał Żychowski"
date: "2023-05-26"
output: html_document
---



---


```{r,warning=FALSE,message=FALSE}
library(readxl)
dane <- read_excel("dane.xlsx")
library(MASS)
library(maptree)
library(rpart)
library(rpart.plot)
library(party)
library(class)
```



```{r}
dane_pierwotne <- data.frame(dane)
Dane <- na.omit(data.frame(dane_pierwotne))
head(Dane)
```



```{r}
Indeksy <- sample(1:nrow(dane),nrow(dane)/2,replace = FALSE)

zbior_uczacy = dane[indexes, ]
zbior_testowy = dane[-indexes, ]

head(zbior_uczacy)
head(zbior_testowy)
```



```{r}
Drzewo <- rpart(zbior_uczacy$`Zatwierdzony kredyt`~.,zbior_uczacy,method = "class")
```



```{r}
Drzewo$parms
Drzewo$numresp
```



```{r}
Model.optimal<-which.min(Drzewo$cptable[,4])
CP.optimal<-Drzewo$cptable[Model.optimal,1]
Drzewo2<-prune(Drzewo,cp=Model.optimal)
```



```{r, results='hold'}
prediction1<-predict(Drzewo,zbior_uczacy,type = "class")

print("Tabela dobroci klasyfikacji")
table(predykacja=prediction1,prawdziwe=zbior_uczacy$`Zatwierdzony kredyt`)

print("Obliczanie błędu predykcji")
error1<-mean(prediction1 != zbior_uczacy$`Zatwierdzony kredyt`)
error1
```


```{r, results='hold'}
prediction2<-predict(Drzewo2,zbior_uczacy,type = "class")

print("Tabela dobroci klasyfikacji")
table(predykacja=prediction2,prawdziwe=zbior_uczacy$`Zatwierdzony kredyt`)

print("Obliczanie błędu predykcji")
error2<-mean(prediction2 != zbior_uczacy$`Zatwierdzony kredyt`)
error2
```



```{r,results='hold'}
TPrediction1<-predict(Drzewo,zbior_testowy,type = "class")
errorT1<-mean(TPrediction1 != zbior_testowy$`Zatwierdzony kredyt`)
print("Błąd predykcji drzewa")
errorT1

TPrediction2<-predict(Drzewo2,zbior_testowy,type = "class")
errorT2<-mean(TPrediction2 != zbior_testowy$`Zatwierdzony kredyt`)
print("Błąd predykcji drzewa Przyciętego")
errorT2
```




```{r, results='hold'}
rpart.plot(Drzewo,type = 4,extra="auto")
rpart.plot(Drzewo2,type = 4,extra="auto")
```





